Implement tag filtering, resolves #115
slovensko-digital/redflags.slovensko.digital pull request #117
Opened 2022-02-14 23:17 UTC by celuchmarek

Projekty vieme na adrese `projekty?tag=xxx` filtrovať podľa tagov `hodnotene-sd`, `hodnotene-rfza`, `hodnotene-komunitou` a prekladajú sa userovi na `Hodnotené tímom Slovensko.Digital`, `Hodnotené tímom Žilina`, `Hodnotené Komunitou`. Zobrazuje sa to takto pod názvom projektu v tabuľke tyrkysovým info badgom:

![Screenshot from 2022-02-14 23-37-25](https://user-images.githubusercontent.com/12500066/153960376-940051be-fe22-4258-9ee5-52eff6cf394d.png)

Keď nie je vybraný žiadny filter, v dropdowne je vybrané `Všetky tagy`:

![Screenshot from 2022-02-14 23-37-45](https://user-images.githubusercontent.com/12500066/153960374-d08c9215-6331-4bfa-b620-c602365fe1db.png)

V detaile projektu je potom tag zobrazený zase ako info badge pod názvom projektu vo vnútri h2, aby to bolo "veľké ako pill":

![Screenshot from 2022-02-14 23-38-20](https://user-images.githubusercontent.com/12500066/153960373-cd512613-325b-4a43-a6f9-e71357902f7c.png)

Ak je tagov viac, sú vedľa seba:

![Screenshot from 2022-02-14 23-38-39](https://user-images.githubusercontent.com/12500066/153960371-d7cb7786-e73a-4ec1-bde2-e1685512bd9f.png)

Keďže sme to mali prekladať zatiaľ staticky v kóde, pridal som do `ProjectsHelper` atribút `self.available_tags` taký dictionary na prekladanie. Ďalej som tam pridal funkciu `translate_tags(tags)`, ktorú potom volám vo views a prekladá tagy projektu na tie translated a rovno ich aj filtruje na tie tri zadané. Ak by sme chceli meniť zoznam tých prekladaných tagov, stačí zmeniť iba v `ProjectsHelper::self.available_tags`.

Filtrovanie sa potom robí v `ProjectsController`, kde sa opýtame, či zadaný parameter tag je v zozname prekladaných. Ak hej, projekty sa podľa neho vyfiltrujú a do atribútu `@filter["tag"]` uložíme aplikovaný tag filter, podľa ktorého sa nastaví selected vo view v dropdown.

2022-02-15 21:08 UTC, jsuchal requested changes

2022-02-15 21:08 UTC, jsuchal commented on app/views/projects/show.html.erb
> +      <% end %>
Row a pomocne classes tu netreba mozes pouzit toto
```
<p class="lead"><span class="badge badge-danger">Hodnotené tímom Slovensko.Digital</span></p>
```

To som uz aj farebne vyladil, len tam hod tie premenne.

2022-02-15 21:08 UTC, jsuchal commented on app/views/projects/index.html.erb
> +        <select name="tag" class="form-control">
Na toto najdes helper

2022-02-15 21:08 UTC, jsuchal commented on app/views/projects/index.html.erb
> +        <input type="submit" value="Filtrovať podľa tagu" class="btn mb-2">
Filtrovat  - koncovemu pouzivatelovi je asi jedno ze to je podla tagu. Proste filtruje.

2022-02-15 21:08 UTC, jsuchal commented on app/views/projects/index.html.erb
> +          <option value="">Všetky tagy</option>
"Zobrazit vsetko"

2022-02-15 21:08 UTC, jsuchal commented on app/controllers/projects_controller.rb
> +    @filter = {
Toto v klude inline do view, nepotrebujeme to mat ako instancnu premennu.

2022-02-15 21:08 UTC, jsuchal commented on app/views/projects/index.html.erb
> +          <% end %>
Tuto to uz asi nedavajme vyzera to byt preplacane.

2022-02-15 21:08 UTC, jsuchal commented on app/views/projects/show.html.erb
> +      <% end %>
Fajn by mozno bolo keby to bol link a ked na to kliknes tak ta prenesie na vsetky projekty s tymto tagom (filtrovany index)

2022-02-15 23:43 UTC, celuchmarek commented on app/controllers/projects_controller.rb
> +    @filter = {
Áno. Ale aj tak tam musela ostať jedna iná premenná, aby sme preniesli aktuálne aplikovaný filter do view.

2022-02-15 23:55 UTC, celuchmarek commented
Zapracoval som pripomienky

1. Konštanta `ALLOWED_TAGS` a vyhodený mapper `translate_tags`, takže tá logika sa robí priamo vo view.
2. Filtrovanie projektov podľa tagov priamo v modeli ešte pred triedením. Je to teraz ale možno trochu viac škaredé, že sa v controlleri opakuje tá časť sortovania projektov.
3. Vyhodená instance variable `@filter`, ale aj tak musela zostať aspoň `@selected_tag`, aby sme vo view vedeli, čo je práve aplikované.
4. Filtrovací form prerobený do helperov a upravené texty podľa návrhov.
5. Vyhodené tagy pri projektoch v indexe.
6. Upravený štýl badgu v show (teraz je danger - červený, a menší) a pridané linky na filtrovaný index podľa daného badgu.

2022-02-16 07:17 UTC, jsuchal requested changes

2022-02-16 07:17 UTC, jsuchal commented on app/controllers/projects_controller.rb
> +    end
Toto stale neodpaluje poriadny select do db ale filtruje to na urovni aplikacie. Predpoklad je, ze to spravi nieco v zmysle `SELECT * FROM projects WHERE <podmienka na tagy a vselico ine>`

2022-02-16 10:34 UTC, celuchmarek commented
Na to, aby som použil ANY na ten array tagov, som tam musel zakomponovať aj ten join, aby som sa od Projects modelu dostal cez ProjectRevisions až do Revisions k atribútu tags. Ale je to teda už filtrované rovno na úrovni databázy.

2022-02-16 10:44 UTC, jsuchal commented on app/controllers/projects_controller.rb
>      if ProjectsHelper::ALLOWED_TAGS.map { |tag, translated| tag }.include? params[:tag]
Tuto ti asi staci ProjectsHelper::ALLOWED_TAGS.keys

2022-02-16 10:45 UTC, jsuchal commented on app/controllers/projects_controller.rb
> +        .where(":tags = ANY(revisions.tags)", tags: params[:tag])
Tu cast co joinuje a filtruje v klude schovaj do scope `with_tag` na urovni Project, ktory toto spravi.

2022-02-16 11:05 UTC, jsuchal commented on app/controllers/projects_controller.rb
> +    end
```suggestion
    @projects = Project.published
    @projects = @projects.with_tag(params[:tag]) if ProjectsHelper::ALLOWED_TAGS.keys.include?(params[:tag])
    @projects = @projects.map { |p| p.published_revision }.sort_by(&:aggregated_rating)    
    end
```

2022-02-16 11:14 UTC, celuchmarek commented
V tom suggestion bol end naviac, tak som to musel u seba spraviť a commitnuť.

2022-02-16 11:17 UTC, jsuchal commented on app/views/projects/show.html.erb
> +        <% end %>
Tuto este to translated daj cez inline, netreba budovat ziadnu mapu.

2022-02-16 12:38 UTC, jsuchal approved these changes

2022-02-16 12:46 UTC, merged