RFZA-36 Odstránenie fáz hodnotení
slovensko-digital/redflags.slovensko.digital pull request #119
Opened 2022-03-06 18:00 UTC by celuchmarek

V zozname projektov som vyhodil prepínanie medzi fázami a teda v tabuľke sa teraz zobrazujú pri projekte všetky jeho existujúce hodnotenia, ktorých môže byť asi od 0 po 24. V strednom stĺpci je `div row` v ktorom sú hodnotenia vo vnútri svojich divov. To sa postará o to, že hodnotenia sú v riadkoch po max 6 (mal som najprv spravenú table vo vnútri toho td, ale toto je jednoduchšie a ľahšie na čítanie kódu). Pri hover alebo tap sa zobrazí tooltip s názvom hodnoteného kritéria.

V detaile projektu sú tiež hodnotenia všetky spolu - nie po fázach. Čo sa týka detailu hodnotení, parser som upravil tak, že vyhodí všetky `h2` tagy, pretože tie boli názvami fáz. Potom pri parsovaní ratingov sa ide čisto cez `h3` tagy s tým, že sa kontroluje, či ten názov máme v RatingTypes.

Aby sa neukladali neurčené ratingy, kontroluje sa, či je tam nejaká žltá alebo sivá hviezdička. (V testoch je dokument, v ktorom je pri hodnotení ikona červenej vlajočky, preto som tam pridal ešte check, že ak tam taká je, je to to isté, ako 4 sivé hviezdičky.)

Doplnil som aj migráciu DB. Ešte zostáva to, že po vykonaní migrácie sa už znova nespúšťa `ProjectRevision::load_from_data(raw)`, takže v body detailu hodnotení ostanú tie fázy ako `h2` tagy. Toto mi zrejme ešte povieš, či treba nejako dorobiť, alebo sa stiahnu nové verzie z platformy a prepíše sa to.

Prikladám takéto dva screenshoty:

![rfza-36_index](https://user-images.githubusercontent.com/12500066/156935664-b5de8e22-b6ed-4f91-8dc4-bb323b26a6bc.png)

![rfza-36_show](https://user-images.githubusercontent.com/12500066/156935662-d9b59e26-c5b3-4169-b00b-f57f012e5193.png)

2022-03-07 15:06 UTC, jsuchal requested changes

2022-03-07 15:06 UTC, jsuchal commented on db/migrate/20220306165121_drop_rating_phases.rb
> +    remove_column :rating_types, :rating_phase_id
Ked vyhodis stlpec tak index aj fk to vyhodi samo.

2022-03-07 15:06 UTC, jsuchal commented on app/models/project_revision.rb
> +    rest = rest.gsub(/<h2>.+?<\/h2>/m, '')
Toto by som nerobil, tie nadpisy odstranime v zdroji.

2022-03-07 15:06 UTC, jsuchal commented on app/views/projects/index.html.erb
> +            <% project.ratings.index_by(&:rating_type).each do |rating_type, rating| %>
Zvazujem ze ci to nespravit tak, ze tam bude 5x 1 hviezdicka, 2x 3hviezdicky ... tak ako mame 5x red flag v poslednom stlpci. A do tooltipu dame tie vsetky nazvy hodnoteni.

2022-03-07 21:31 UTC, celuchmarek commented
Takto by to vyzeralo v súčasnom stave:

![Screenshot from 2022-03-07 22-26-55](https://user-images.githubusercontent.com/12500066/157120957-f7389148-cd87-456c-800d-3d74600fa139.png)

2022-03-08 08:41 UTC, jsuchal approved these changes

2022-03-08 08:42 UTC, merged