SD-2693/Update-job-for-drafts-and-exports
slovensko-digital/redflags.slovensko.digital pull request #149
Opened 2024-07-08 22:23 UTC by tomasdrga

Created update job, introduce api token auth, to use sync routes as webhooks for app script sheet change

2024-07-10 14:41 UTC, tomasdrga commented
V tomto PR som spravil update job google sheetov, ktory bude bezat cez clock nech sa zabezpeci, ze udaje v tabulkach su aktualne

2024-07-11 06:16 UTC, celuchmarek requested changes

2024-07-11 06:16 UTC, celuchmarek commented on app/jobs/sync_sheets_project_info_job.rb
> +    pages = Page.all.select{ |page| page.phase.present? }
toto sa dá prepísať aj na where, že? Model.all ti vyberie z DB všetky záznamy a select už pracuje na rubz poľom. Where vyskladá query, ktorú pustí priamo v DB a tak to do aplikácie prídu už iba relevantné záznamy.

2024-07-11 06:16 UTC, celuchmarek commented on app/jobs/sync_sheets_project_info_job.rb
> +    pages.each do |page|
osobne by som nevytváral premennú pages, ale dal to rovno sem - nie je to také dlhé

2024-07-11 06:16 UTC, celuchmarek commented on app/models/page.rb
> -      },
prečo ide toto preč?

2024-07-11 06:16 UTC, celuchmarek commented on config/clock.rb
> +  every(1.week, 'redflags:sync', at: '2:00')
prečo raz týždenne?

2024-07-11 06:16 UTC, celuchmarek commented on app/controllers/admin_controller.rb
> +    if request.headers['X-API-Token'].present?
potrebujeme custom header? Pozi napr tu: https://github.com/slovensko-digital/govbox-pro/blob/main/app/controllers/api_controller.rb#L26  Tá prvá polovica berie token asi z Authorization header a druhá z parametru token keď tak. Tak sme si zvykli vo viacerých projektoch.

2024-07-24 11:18 UTC, tomasdrga commented on app/models/page.rb
> -      },
Tento stlpec, uz nie je v sheetoch, bol nepotrebny

2024-07-24 11:20 UTC, tomasdrga commented on config/clock.rb
> +  every(1.week, 'redflags:sync', at: '2:00')
Klasicky redflags sync, som dal z clocku uplne prec, odsledoval som to a z platformy uz nechceme nic syncovat, zbytocne to hadze diskusie, ktore tam su vedene ale ziadne hodnotenia, je to nahradene syncom google draftov

2024-07-24 11:21 UTC, tomasdrga commented on app/controllers/admin_controller.rb
> +    if request.headers['X-API-Token'].present?
Toto bol pokus ako remote spustit sync job, ked sa vytvori, nejaky projekt v shetoch, no po mnozstvach pokusov, to na teraz zostane syncnute len kazdy den automaticky

2024-07-25 06:44 UTC, celuchmarek commented on app/controllers/admin_controller.rb
> +    if request.headers['X-API-Token'].present?
jo, prípadne si admin vie manuálne spustiť sync, že?

2024-07-25 06:45 UTC, celuchmarek approved these changes

2024-07-25 06:45 UTC, tomasdrga commented on app/controllers/admin_controller.rb
> +    if request.headers['X-API-Token'].present?
jo, manualne spustenie zostalo

2024-08-01 14:25 UTC, merged